### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by iBotPeaches** [sourcetoad/react-native-idscan-sdk#3]
- [x] Update to latest RN
- [x] Determine proper package name (`com.sourcetoad.idscansdk-rn`) ?
- [ ] Support auto versioning on tag push
